// examples/react/src/PlaybackControls.tsx
import { BEHAVIOR_OPTIONS } from '@chat-scroll/example-shared'
import type { ChatScrollBehavior } from '@chat-scroll/core'
import type { UsePlaybackReturn } from './use-playback'

/**
 * Renders the shared three-widget playback strip: interval input,
 * smooth/instant select, Pause/Resume toggle. Every React scenario
 * uses this so the controls are visually identical across demos.
 */
export function PlaybackControls({ playback }: { playback: UsePlaybackReturn }) {
  return (
    <>
      <label className="playback">
        interval
        <input
          type="number"
          min={10}
          max={2000}
          step={10}
          data-test="interval"
          value={playback.intervalMs}
          onChange={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 10) playback.setIntervalMs(n)
          }}
        />
        ms
      </label>
      <label className="behavior">
        scroll
        <select
          data-test="behavior"
          value={playback.scrollBehavior}
          onChange={(e) =>
            playback.setScrollBehavior(
              e.currentTarget.value as ChatScrollBehavior,
            )
          }
        >
          {BEHAVIOR_OPTIONS.map((b) => (
            <option key={b} value={b}>
              {b}
            </option>
          ))}
        </select>
      </label>
      <label className="duration">
        duration
        <input
          type="number"
          min={0}
          max={2000}
          step={20}
          data-test="duration"
          value={playback.scrollDurationMs}
          onChange={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 0) playback.setScrollDurationMs(n)
          }}
        />
        ms
      </label>
      {playback.supportsGutter ? (
        <label className="gutter-toggle">
          <input
            type="checkbox"
            data-test="show-gutter"
            checked={playback.showGutter}
            onChange={(e) => playback.setShowGutter(e.currentTarget.checked)}
          />
          show gutter
        </label>
      ) : null}
      <button
        data-test="auto-tick"
        data-running={playback.running ? 'true' : 'false'}
        onClick={() => playback.toggle()}
      >
        {playback.running ? 'Pause stream' : 'Resume stream'}
      </button>
    </>
  )
}

// examples/vue/src/PlaybackControls.vue
<script setup lang="ts">
import { BEHAVIOR_OPTIONS } from '@chat-scroll/example-shared'
import type { ChatScrollBehavior } from '@chat-scroll/core'
import type { UsePlaybackReturn } from './use-playback'

const props = defineProps<{ playback: UsePlaybackReturn }>()

function onIntervalInput(e: Event) {
  const n = Number((e.target as HTMLInputElement).value)
  if (Number.isFinite(n) && n >= 10) props.playback.setIntervalMs(n)
}

function onBehaviorChange(e: Event) {
  const v = (e.target as HTMLSelectElement).value as ChatScrollBehavior
  props.playback.setScrollBehavior(v)
}

function onDurationInput(e: Event) {
  const n = Number((e.target as HTMLInputElement).value)
  if (Number.isFinite(n) && n >= 0) props.playback.setScrollDurationMs(n)
}
</script>

<template>
  <label class="playback">
    interval
    <input
      type="number"
      min="10"
      max="2000"
      step="10"
      data-test="interval"
      :value="props.playback.intervalMs.value"
      @input="onIntervalInput"
    />
    ms
  </label>
  <label class="behavior">
    scroll
    <select
      data-test="behavior"
      :value="props.playback.scrollBehavior.value"
      @change="onBehaviorChange"
    >
      <option v-for="b in BEHAVIOR_OPTIONS" :key="b" :value="b">{{ b }}</option>
    </select>
  </label>
  <label class="duration">
    duration
    <input
      type="number"
      min="0"
      max="2000"
      step="20"
      data-test="duration"
      :value="props.playback.scrollDurationMs.value"
      @input="onDurationInput"
    />
    ms
  </label>
  <label v-if="props.playback.supportsGutter" class="gutter-toggle">
    <input
      type="checkbox"
      data-test="show-gutter"
      :checked="props.playback.showGutter.value"
      @change="
        (e) =>
          props.playback.setShowGutter(
            (e.target as HTMLInputElement).checked,
          )
      "
    />
    show gutter
  </label>
  <button
    data-test="auto-tick"
    :data-running="props.playback.running.value ? 'true' : 'false'"
    @click="props.playback.toggle()"
  >
    {{ props.playback.running.value ? 'Pause stream' : 'Resume stream' }}
  </button>
</template>
