// examples/solid/src/PlaybackControls.tsx
import { For } from 'solid-js'
import { BEHAVIOR_OPTIONS } from '@chat-scroll/example-shared'
import type { ChatScrollBehavior } from '@chat-scroll/core'
import type { UsePlaybackReturn } from './use-playback'

/**
 * Renders the shared three-widget playback strip: interval input,
 * smooth/instant select, Pause/Resume toggle. Every Solid scenario
 * uses this so the controls are visually identical across demos.
 */
export function PlaybackControls(props: { playback: UsePlaybackReturn }) {
  return (
    <>
      <label class="playback">
        interval
        <input
          type="number"
          min="10"
          max="2000"
          step="10"
          data-test="interval"
          value={props.playback.intervalMs()}
          onInput={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 10) props.playback.setIntervalMs(n)
          }}
        />
        ms
      </label>
      <label class="behavior">
        scroll
        <select
          data-test="behavior"
          value={props.playback.scrollBehavior()}
          onChange={(e) =>
            props.playback.setScrollBehavior(
              e.currentTarget.value as ChatScrollBehavior,
            )
          }
        >
          <For each={BEHAVIOR_OPTIONS}>
            {(b) => <option value={b}>{b}</option>}
          </For>
        </select>
      </label>
      <label class="duration">
        duration
        <input
          type="number"
          min="0"
          max="2000"
          step="20"
          data-test="duration"
          value={props.playback.scrollDurationMs()}
          onInput={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 0)
              props.playback.setScrollDurationMs(n)
          }}
        />
        ms
      </label>
      {props.playback.supportsGutter ? (
        <label class="gutter-toggle">
          <input
            type="checkbox"
            data-test="show-gutter"
            checked={props.playback.showGutter()}
            onChange={(e) =>
              props.playback.setShowGutter(e.currentTarget.checked)
            }
          />
          show gutter
        </label>
      ) : null}
      <button
        data-test="auto-tick"
        attr:data-running={props.playback.running() ? 'true' : 'false'}
        onClick={() => props.playback.toggle()}
      >
        {props.playback.running() ? 'Pause stream' : 'Resume stream'}
      </button>
    </>
  )
}

// examples/react/src/PlaybackControls.tsx
import { BEHAVIOR_OPTIONS } from '@chat-scroll/example-shared'
import type { ChatScrollBehavior } from '@chat-scroll/core'
import type { UsePlaybackReturn } from './use-playback'

/**
 * Renders the shared three-widget playback strip: interval input,
 * smooth/instant select, Pause/Resume toggle. Every React scenario
 * uses this so the controls are visually identical across demos.
 */
export function PlaybackControls({ playback }: { playback: UsePlaybackReturn }) {
  return (
    <>
      <label className="playback">
        interval
        <input
          type="number"
          min={10}
          max={2000}
          step={10}
          data-test="interval"
          value={playback.intervalMs}
          onChange={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 10) playback.setIntervalMs(n)
          }}
        />
        ms
      </label>
      <label className="behavior">
        scroll
        <select
          data-test="behavior"
          value={playback.scrollBehavior}
          onChange={(e) =>
            playback.setScrollBehavior(
              e.currentTarget.value as ChatScrollBehavior,
            )
          }
        >
          {BEHAVIOR_OPTIONS.map((b) => (
            <option key={b} value={b}>
              {b}
            </option>
          ))}
        </select>
      </label>
      <label className="duration">
        duration
        <input
          type="number"
          min={0}
          max={2000}
          step={20}
          data-test="duration"
          value={playback.scrollDurationMs}
          onChange={(e) => {
            const n = Number(e.currentTarget.value)
            if (Number.isFinite(n) && n >= 0) playback.setScrollDurationMs(n)
          }}
        />
        ms
      </label>
      {playback.supportsGutter ? (
        <label className="gutter-toggle">
          <input
            type="checkbox"
            data-test="show-gutter"
            checked={playback.showGutter}
            onChange={(e) => playback.setShowGutter(e.currentTarget.checked)}
          />
          show gutter
        </label>
      ) : null}
      <button
        data-test="auto-tick"
        data-running={playback.running ? 'true' : 'false'}
        onClick={() => playback.toggle()}
      >
        {playback.running ? 'Pause stream' : 'Resume stream'}
      </button>
    </>
  )
}
