// examples/vue/src/RichMessageView.vue
<script setup lang="ts">
import type { Part, RichMessage, ThinkingPart, ToolPart } from './use-rich-chat'
import RichBlock from './RichBlock.vue'

defineProps<{ msg: RichMessage }>()

// Narrowing helpers used in the template. `v-if="part.type === 'text'"`
// keeps Vue's template type narrowing inside that branch.
const isText = (p: Part): p is Extract<Part, { type: 'text' }> =>
  p.type === 'text'
const isBlock = (p: Part): p is ThinkingPart | ToolPart =>
  p.type === 'thinking' || p.type === 'tool'
</script>

<template>
  <div
    :class="msg.role === 'user' ? 'msg msg--user' : 'msg msg--bot'"
    :data-test="msg.role === 'user' ? 'user-msg' : 'bot-msg'"
  >
    <!--
      `:key="i"` keeps each slot stable across streaming updates. The
      part object at index N is replaced on every chunk (immutable
      update), but the DOM node and the child component instance — and
      its local `open` ref — survive.
    -->
    <template v-for="(part, i) in msg.parts" :key="i">
      <div v-if="isText(part)" class="msg__text">
        {{ part.text }}
      </div>
      <RichBlock v-else-if="isBlock(part)" :part="part" :index="i" />
    </template>
  </div>
</template>

// examples/react/src/RichMessageView.tsx
import { useState } from 'react'
import type { RichMessage, ThinkingPart, ToolPart } from './use-rich-chat'

export function MessageView({ msg }: { msg: RichMessage }) {
  return (
    <div
      className={msg.role === 'user' ? 'msg msg--user' : 'msg msg--bot'}
      data-test={msg.role === 'user' ? 'user-msg' : 'bot-msg'}
    >
      {/*
        Index keys keep each slot stable across streaming updates. The
        part object at index N is replaced on every chunk (immutable
        update), but the DOM node and the child component instance — and
        its local `open` state — survive.
      */}
      {msg.parts.map((part, i) =>
        part.type === 'text' ? (
          <div key={i} className="msg__text">
            {part.text}
          </div>
        ) : (
          <Block key={i} part={part} index={i} />
        ),
      )}
    </div>
  )
}

function Block({
  part,
  index,
}: {
  part: ThinkingPart | ToolPart
  index: number
}) {
  const [open, setOpen] = useState(part.defaultOpen)
  const title = part.type === 'thinking' ? part.summary : part.name
  const args = part.type === 'tool' ? part.args : ''
  const body = part.type === 'thinking' ? part.body : part.result

  return (
    <div
      className={
        part.type === 'thinking' ? 'block block--thinking' : 'block block--tool'
      }
      data-test="expand-block"
      data-block-index={index}
      data-open={open ? 'true' : 'false'}
    >
      <button
        className="block__summary"
        type="button"
        aria-expanded={open}
        onClick={() => setOpen(!open)}
      >
        <span className="block__icon" aria-hidden="true">
          {part.type === 'thinking' ? '💭' : '🛠'}
        </span>
        <span className="block__title">
          {title}
          {part.type === 'tool' ? (
            <span className="block__args">{args}</span>
          ) : null}
        </span>
        <span className="block__chev" aria-hidden="true">
          ▾
        </span>
      </button>
      <div className="block__wrap">
        <div className="block__body">
          {part.type === 'tool' ? (
            <pre className="block__pre">{body}</pre>
          ) : (
            body
          )}
        </div>
      </div>
    </div>
  )
}
